version: '3.8'
services:
  server:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - APP_ENV=development
      - DEV_DB_HOST=postgres
      - DEV_DB_PORT=5432
      - DEV_DB_USER=postgres
      - DEV_DB_PASSWORD=secret
      - DEV_DB_NAME=tradeinsight_dev
    depends_on:
      - postgres
    networks:
      - tradeinsight-network

  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=tradeinsight_dev
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - tradeinsight-network

volumes:
  postgres-data:

networks:
  tradeinsight-network:
    driver: bridge
